name: PR checks

on:
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Get yarn cache directory path
        id: yarn-cache-dir-path
        run: echo "::set-output name=dir::$(yarn cache dir)"
      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '14'
      - uses: actions/cache@v2
        id: yarn-cache
        with:
          path: ${{ steps.yarn-cache-dir-path.outputs.dir }}
          key: ${{ runner.os }}-yarn-${{ hashFiles('**/yarn.lock') }}
          restore-keys: |
            ${{ runner.os }}-yarn-
      - name: 'monorepo: yarn install'
        run: yarn --prefer-offline --frozen-lockfile
      - name: 'backend: lint'
        run: cd packages/backend && yarn lint
      - name: 'electron-client: lint'
        run: cd packages/electron-client && yarn lint
      - name: 'backend: build'
        run: CI=false cd packages/backend && yarn build
      - name: 'electron-client: build'
        run: CI=false cd packages/electron-client && yarn build